/**
 * AGENT — A Real Estate Career Game
 * City-specific card decks — 80 cards across 5 cities (8 trouble + 8 victory each).
 */

import type { CardDef, CityId } from './game-types';

// ── NEW YORK ──────────────────────────────────────────────────────────────

const NEW_YORK_CARDS: CardDef[] = [
  // TROUBLE CARDS
  {
    id: 'ny-trap-coop-rejection',
    name: 'Co-op Board Rejection',
    type: 'trap',
    emoji: '🏢',
    description: 'The board found your buyer\'s finances acceptable but their lifestyle… less so.',
    flavorText: '"Thirty-six pages of due diligence. Three interviews. Rejected."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 20,
      message: 'Your buyer passed financing but bombed the co-op board interview. Deal dead. That\'s a lost quarter.',
    },
    weight: 8,
  },
  {
    id: 'ny-trap-bidding-burnout',
    name: 'Bidding War Burnout',
    type: 'trap',
    emoji: '😤',
    description: 'Submitted seven offers for this client. Seven times at the table, seven losses.',
    flavorText: '"They\'re starting to blame you."',
    effect: {
      burnoutDelta: 22,
      addTierB: -1,
      message: 'Your buyer lost seven consecutive bidding wars. They\'re demoralized. One dropped from your pipeline.',
    },
    weight: 7,
  },
  {
    id: 'ny-trap-attorney-delay',
    name: 'Attorney Delay',
    type: 'trap',
    emoji: '⚖️',
    description: 'New York requires an attorney review period. Theirs is on vacation. In Capri.',
    flavorText: '"For two more weeks."',
    effect: {
      addTierA: 1,
      addPendingDeals: -1,
      burnoutDelta: 10,
      message: 'Attorney review delay. Your deal slipped back to A-tier. Closing pushed to next quarter.',
    },
    weight: 7,
  },
  {
    id: 'ny-trap-mansion-tax',
    name: 'Mansion Tax Shock',
    type: 'trap',
    emoji: '💸',
    description: 'They didn\'t budget for the mansion tax. On a $2M purchase, that\'s $25,000 they don\'t have.',
    flavorText: '"Surprise."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      message: 'Buyer blindsided by mansion tax on a $2M deal. They walked. Always educate on closing costs upfront.',
    },
    weight: 6,
  },
  {
    id: 'ny-trap-management-block',
    name: 'Management Company Interference',
    type: 'trap',
    emoji: '📋',
    description: 'The listing is technically available. The building management company has a different opinion.',
    flavorText: '"And they run everything."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 12,
      addTierA: 1,
      message: 'Building management created roadblocks on your deal. Lost this one, but the seller is still yours next quarter.',
    },
    weight: 6,
  },
  {
    id: 'ny-trap-gazumping',
    name: 'Gazumping — Outbid After Acceptance',
    type: 'trap',
    emoji: '😱',
    description: 'They accepted your offer verbally. No signed contract yet. A cash buyer appeared and offered $80K over.',
    flavorText: '"Your buyer got gazumped."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 18,
      message: 'Cash buyer swooped in after verbal acceptance. No contract, no protection. Brutal New York reality.',
    },
    weight: 7,
  },
  {
    id: 'ny-trap-disclosure-dispute',
    name: 'Disclosure Dispute',
    type: 'trap',
    emoji: '📰',
    description: 'The seller knew about the water damage. They disclosed "moisture concerns." Your buyer\'s lawyer disagrees.',
    flavorText: '"On the semantics."',
    effect: {
      burnoutDelta: 20,
      addCash: -5000,
      message: 'Disclosure dispute tied up your deal in legal review. $5,000 in legal costs. Document everything.',
    },
    weight: 6,
  },
  {
    id: 'ny-trap-inventory-famine',
    name: 'Inventory Famine',
    type: 'trap',
    emoji: '🏚️',
    description: 'You have six pre-approved buyers and nothing to show them. Four months of inventory.',
    flavorText: '"Supply is brutally low."',
    effect: {
      marketMultiplier: 0.65,
      marketMultiplierRounds: 2,
      burnoutDelta: 12,
      message: 'Inventory famine hits. Buyers can\'t find homes, you can\'t close deals. Market suppressed for 2 quarters.',
    },
    weight: 6,
  },
  // VICTORY CARDS
  {
    id: 'ny-opp-offmarket-townhouse',
    name: 'Off-Market Townhouse',
    type: 'opportunity',
    emoji: '🗝️',
    description: 'Your network paid off. A seller reached out before listing — wants to sell quietly.',
    flavorText: '"You have 48 hours."',
    effect: {
      addCash: 38000,
      burnoutDelta: -5,
      message: 'Off-market townhouse. Full commission, no bidding war. That\'s what relationships buy you in New York.',
    },
    weight: 5,
  },
  {
    id: 'ny-lead-allcash',
    name: 'All-Cash Offer Accepted',
    type: 'lead',
    emoji: '💵',
    description: 'A Goldman exec needs an apartment this week. Has the cash. Doesn\'t want to negotiate.',
    flavorText: '"Just close."',
    effect: {
      addPendingDeals: 1,
      addCash: 25000,
      message: 'All-cash buyer, fast close. Already in pending. Collect the commission. That\'s a New York minute.',
    },
    weight: 5,
  },
  {
    id: 'ny-opp-bidding-win',
    name: 'West Side Story (Bidding War Win)',
    type: 'opportunity',
    emoji: '🏆',
    description: 'You coached your buyers perfectly. Escalation clause. Strong personal letter. Waived inspection.',
    flavorText: '"Won against eleven offers."',
    effect: {
      addCash: 42000,
      burnoutDelta: -10,
      addTierB: 2,
      message: 'Your buyers won an 11-offer bidding war. The escalation clause closed it. Big commission, bigger reputation.',
    },
    weight: 5,
  },
  {
    id: 'ny-lead-pied-a-terre',
    name: 'Pied-à-Terre Deal',
    type: 'lead',
    emoji: '🌃',
    description: 'A European client needs a New York pied-à-terre. Budget: unlimited. Timeline: now.',
    flavorText: '"Make it happen."',
    effect: {
      addTierA: 1,
      addPendingDeals: 1,
      addCash: 15000,
      message: 'European buyer, pied-à-terre purchase, no price resistance. A-tier with a bonus advance.',
    },
    weight: 5,
  },
  {
    id: 'ny-lead-film-referral',
    name: 'Film Industry Referral',
    type: 'lead',
    emoji: '🎬',
    description: 'A casting director you helped move referred their entire network. Four actors need apartments.',
    flavorText: '"This city runs on relationships."',
    effect: {
      addTierB: 4,
      addTierC: 6,
      burnoutDelta: -8,
      message: 'Film industry referral wave: 4 B-tier leads, 6 C-tier contacts. New York is a small town if you know the right people.',
    },
    weight: 5,
  },
  {
    id: 'ny-lead-prewar-listing',
    name: 'Pre-War Trophy Listing',
    type: 'lead',
    emoji: '🏛️',
    description: 'You landed the listing on a 1920s pre-war building on the Upper East Side.',
    flavorText: '"The press will cover this one."',
    effect: {
      addTierA: 1,
      addCash: 20000,
      addTierB: 3,
      addTierC: 8,
      message: 'Pre-war trophy listing secured. Earn the GCI, gain the exposure. Your best marketing piece this year.',
    },
    weight: 5,
  },
  {
    id: 'ny-opp-corporate-relo',
    name: 'Corporate Relocation Contract',
    type: 'opportunity',
    emoji: '✈️',
    description: 'A Fortune 100 company contracted you as their NYC relocation agent. 12 executives moving in Q1.',
    flavorText: '"This is a season-changer."',
    effect: {
      addTierB: 6,
      addTierC: 10,
      burnoutDelta: 5,
      message: 'Corporate relo contract landed. 16 leads flood your pipeline. Set the system and work it.',
    },
    weight: 5,
  },
  {
    id: 'ny-opp-condo-launch',
    name: 'Luxury Condo Launch Party',
    type: 'opportunity',
    emoji: '🥂',
    description: 'The developer invited you to their launch event. Preferred buyer\'s agent for 40 units.',
    flavorText: '"New York developers play big."',
    effect: {
      addTierC: 15,
      addTierB: 5,
      addCash: 10000,
      message: 'Condo launch partnership. 20 new contacts, a preferred-agent retainer, and a referral bonus.',
    },
    weight: 5,
  },
];

// ── BEVERLY HILLS ─────────────────────────────────────────────────────────

const BEVERLY_HILLS_CARDS: CardDef[] = [
  // TROUBLE CARDS
  {
    id: 'bh-trap-tabloid',
    name: 'Celebrity Deal Goes Tabloid',
    type: 'trap',
    emoji: '📸',
    description: 'Your client\'s purchase was photographed by a paparazzo. Now the seller wants out.',
    flavorText: '"Confidentiality is everything in Beverly Hills."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 20,
      message: 'Paparazzi blew your deal. The seller panicked about publicity. Confidentiality is everything.',
    },
    weight: 7,
  },
  {
    id: 'bh-trap-perfection',
    name: 'Client Demands Perfection',
    type: 'trap',
    emoji: '😤',
    description: 'They viewed 47 properties. Nothing is "right." The guest wing isn\'t big enough.',
    flavorText: '"The view is 10% water, not 15%."',
    effect: {
      addTierB: -2,
      burnoutDelta: 25,
      message: 'Demanding luxury clients walked after 47 showings. Two B-tier leads dropped. Your time has value too.',
    },
    weight: 7,
  },
  {
    id: 'bh-trap-leak',
    name: 'Off-Market Deal Leaks',
    type: 'trap',
    emoji: '🤫',
    description: 'Someone talked. Your pocket listing hit social media before you were ready.',
    flavorText: '"Five other agents are now calling your seller."',
    effect: {
      addTierA: -1,
      burnoutDelta: 15,
      addCash: -3000,
      message: 'Your off-market advantage leaked. Lost the exclusive, lost time, had to spend to re-establish position.',
    },
    weight: 7,
  },
  {
    id: 'bh-trap-art-dispute',
    name: 'Art Collection Dispute',
    type: 'trap',
    emoji: '🖼️',
    description: 'The seller included the Basquiat in the original showing. Their attorney says it\'s a separate transaction.',
    flavorText: '"The buyer is furious."',
    effect: {
      burnoutDelta: 18,
      addCash: -8000,
      message: 'Art collection dispute halted closing. $8K in escrow delays and legal fees. Get everything in writing.',
    },
    weight: 6,
  },
  {
    id: 'bh-trap-designer-veto',
    name: 'Design Consultant Veto',
    type: 'trap',
    emoji: '🏗️',
    description: 'Your buyer\'s interior designer toured the home and gave one word: "No."',
    flavorText: '"The buyer listens to the designer."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      message: 'Interior designer killed the deal. In Beverly Hills, the designer\'s veto is absolute.',
    },
    weight: 7,
  },
  {
    id: 'bh-trap-zoning',
    name: 'Guest House Zoning Issue',
    type: 'trap',
    emoji: '📋',
    description: 'The guest house was added without permits. The buyer\'s attorney found it in title search.',
    flavorText: '"Deal in jeopardy."',
    effect: {
      addTierA: 1,
      addPendingDeals: -1,
      burnoutDelta: 20,
      message: 'Unpermitted guest house discovered. Deal pushed back one quarter. Seller has to remediate.',
    },
    weight: 6,
  },
  {
    id: 'bh-trap-poaching',
    name: 'Agent Poaching',
    type: 'trap',
    emoji: '🦹',
    description: 'Another luxury agent approached your A-tier client at a charity gala.',
    flavorText: '"We\'re evaluating our options."',
    effect: {
      addTierA: -1,
      burnoutDelta: 20,
      message: 'A-tier client being poached by a competitor. Stay close to your top leads.',
    },
    weight: 7,
  },
  {
    id: 'bh-trap-hedgefund',
    name: 'Hedge Fund Buyer Falls Through',
    type: 'trap',
    emoji: '📉',
    description: 'The hedge fund\'s Q3 numbers came in. The managing partner\'s bonus was restructured.',
    flavorText: '"The $9M home is suddenly \'under review.\'"',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 22,
      addCash: -5000,
      message: 'Hedge fund buyer\'s finances shifted. Lost a $9M deal. Beverly Hills deals are huge — so are the losses.',
    },
    weight: 6,
  },
  // VICTORY CARDS
  {
    id: 'bh-opp-offmarket',
    name: 'Off-Market Score',
    type: 'opportunity',
    emoji: '🗝️',
    description: 'A pocket listing lands in your lap from a fellow luxury agent. No competition.',
    flavorText: '"Network pays dividends."',
    effect: {
      addCash: 50000,
      addPendingDeals: 1,
      message: 'Off-market pocket listing. $50K GCI in the pipeline. No other agents, no bidding war.',
    },
    weight: 5,
  },
  {
    id: 'bh-opp-celebrity',
    name: 'Celebrity Discretionary Purchase',
    type: 'opportunity',
    emoji: '⭐',
    description: 'An A-list actor saw a listing you sent and made an offer in 24 hours. Cash.',
    flavorText: '"No contingencies. Just a check and a handshake."',
    effect: {
      addCash: 75000,
      burnoutDelta: -10,
      message: 'Celebrity buyer, cash close, 24-hour decision. This is why you built in Beverly Hills. $75K GCI, done.',
    },
    weight: 4,
  },
  {
    id: 'bh-opp-ad-feature',
    name: 'Architectural Digest Feature',
    type: 'opportunity',
    emoji: '📰',
    description: 'Your listing was featured in Architectural Digest. Fourteen qualified buyers called.',
    flavorText: '"Your phone hasn\'t stopped."',
    effect: {
      addTierB: 5,
      addTierC: 12,
      burnoutDelta: -5,
      message: 'Architectural Digest feature generated 17 inbound leads. Luxury marketing pays at scale.',
    },
    weight: 5,
  },
  {
    id: 'bh-lead-billionaire',
    name: 'Billionaire Compound Listing',
    type: 'lead',
    emoji: '🏰',
    description: 'An estate attorney referred you to the estate of a deceased billionaire.',
    flavorText: '"Their compound is going on the market."',
    effect: {
      addTierA: 1,
      addCash: 30000,
      addTierC: 10,
      message: 'Billionaire estate listing. Prestige, commission, and every luxury buyer in the region will call.',
    },
    weight: 5,
  },
  {
    id: 'bh-lead-tech-founder',
    name: 'Tech Founder Relocation',
    type: 'lead',
    emoji: '💻',
    description: 'A tech founder exited their company for $400M. Budget: $12M. Timeline: 30 days.',
    flavorText: '"Moving from San Francisco."',
    effect: {
      addTierA: 2,
      addPendingDeals: 1,
      addCash: 20000,
      message: 'Tech founder relo. $12M budget. 30 days to close. Already got one offer in.',
    },
    weight: 5,
  },
  {
    id: 'bh-lead-studio-exec',
    name: 'Studio Exec Compound',
    type: 'lead',
    emoji: '🎬',
    description: 'A studio chairman is quietly looking. Budget: $8M. Prefers off-market.',
    flavorText: '"Referred by their attorney."',
    effect: {
      addTierA: 1,
      addCash: 15000,
      burnoutDelta: -8,
      message: 'Studio executive looking for an off-market compound. Attorney referral means trust is pre-built.',
    },
    weight: 5,
  },
  {
    id: 'bh-opp-international',
    name: 'International Buyer — No Contingencies',
    type: 'opportunity',
    emoji: '🌍',
    description: 'A Saudi buyer\'s family wants a California property as a lifestyle asset. Cash offer.',
    flavorText: '"No inspection, no financing contingency. Closes in 14 days."',
    effect: {
      addCash: 65000,
      addPendingDeals: 1,
      burnoutDelta: -5,
      message: 'International cash buyer, 14-day close. Clean deal, full commission.',
    },
    weight: 5,
  },
  {
    id: 'bh-opp-rental-portfolio',
    name: 'Luxury Rental Portfolio',
    type: 'opportunity',
    emoji: '🏘️',
    description: 'An entertainment attorney wants to build a luxury rental portfolio — on retainer.',
    flavorText: '"This is leverage."',
    effect: {
      addPassiveIncomeMonthly: 3000,
      addTierB: 3,
      burnoutDelta: -10,
      message: 'Retained as acquisition agent for luxury rental portfolio. $3K/mo retainer + ongoing deal flow.',
    },
    weight: 4,
  },
];

// ── KANSAS CITY ───────────────────────────────────────────────────────────

const KANSAS_CITY_CARDS: CardDef[] = [
  // TROUBLE CARDS
  {
    id: 'kc-trap-builder-sours',
    name: 'Builder Relationship Sours',
    type: 'trap',
    emoji: '🔨',
    description: 'You missed three builder-client meetings this quarter.',
    flavorText: '"Going a different direction on referrals."',
    effect: {
      addTierB: -3,
      burnoutDelta: 15,
      message: 'Builder relationship lost from neglect. Three B-tier referrals gone. Relationships need maintenance.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-price-reduction',
    name: 'Price Reduction Demand',
    type: 'trap',
    emoji: '📉',
    description: 'Your listing has been sitting 45 days. The seller wants to lower the price — by $50K.',
    flavorText: '"They blame the market. And you."',
    effect: {
      addCash: -3000,
      burnoutDelta: 18,
      message: 'Price reduction on a slow listing. Lost commission on the delta plus the emotional drain.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-subdivision',
    name: 'New Subdivision Flood',
    type: 'trap',
    emoji: '🏗️',
    description: 'Three major builders broke ground. Now 400 new homes compete with your listings.',
    flavorText: '"Existing inventory can\'t compete."',
    effect: {
      marketMultiplier: 0.80,
      marketMultiplierRounds: 2,
      burnoutDelta: 10,
      message: 'New subdivision flood. Existing home market drops 20% for 2 quarters. Pivot to builder relationships.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-weather',
    name: 'Midwest Weather Delay',
    type: 'trap',
    emoji: '❄️',
    description: 'Three consecutive ice storms. No one is leaving their house, let alone touring homes.',
    flavorText: '"Your January was already bad — now it\'s worse."',
    effect: {
      marketMultiplier: 0.60,
      marketMultiplierRounds: 1,
      burnoutDelta: 12,
      message: 'Ice storms shut down the market for a quarter. 40% suppression. Use the time to prospect your database.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-inspection',
    name: 'Inspection Surprise',
    type: 'trap',
    emoji: '🔍',
    description: 'The inspector found foundation cracks. Seller won\'t repair. Buyer won\'t waive.',
    flavorText: '"You\'re holding a dead deal together with prayer."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      message: 'Foundation issues killed your deal. Inspection surprises are the #1 cause of dead deals in older midwest markets.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-appraisal',
    name: 'Low Appraisal',
    type: 'trap',
    emoji: '📊',
    description: 'Appraisal came in $18,000 below contract price. Seller won\'t come down.',
    flavorText: '"Three months of work, gone."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 20,
      message: 'Appraisal gap killed the deal. $18K difference, neither side would move. Know your comps.',
    },
    weight: 7,
  },
  {
    id: 'kc-trap-layoffs',
    name: 'Corporate Layoff Wave',
    type: 'trap',
    emoji: '💼',
    description: 'A major local employer announced layoffs. Three of your pre-approved buyers just lost their jobs.',
    flavorText: '"Their purchasing timelines evaporated."',
    effect: {
      addTierB: -2,
      addTierA: -1,
      burnoutDelta: 18,
      message: 'Corporate layoff wave hit your pipeline. Two B-tier and one A-tier lead dropped out.',
    },
    weight: 6,
  },
  {
    id: 'kc-trap-zoning',
    name: 'Agricultural Zoning Surprise',
    type: 'trap',
    emoji: '🌾',
    description: 'The rural property has an agricultural zoning overlay that prevents the barn renovation they planned.',
    flavorText: '"Deal off."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 12,
      message: 'Agricultural zoning killed the rural deal. Always check zoning before your client falls in love.',
    },
    weight: 6,
  },
  // VICTORY CARDS
  {
    id: 'kc-opp-builder-lots',
    name: 'Builder Relationship — Lot Exclusives',
    type: 'opportunity',
    emoji: '🏗️',
    description: 'Southern Builders gave you exclusive buyer\'s agent access to their next 12 lots.',
    flavorText: '"Monthly buyers, recurring income."',
    effect: {
      addTierB: 4,
      addTierC: 8,
      addCash: 12000,
      message: 'Southern Builders exclusive. 12 lots, recurring buyers. $12K advance plus deal flow for two quarters.',
    },
    weight: 6,
  },
  {
    id: 'kc-lead-anchor-listing',
    name: 'Neighborhood Anchor Listing',
    type: 'lead',
    emoji: '🏡',
    description: 'You landed the listing on the most desirable street in Brookside.',
    flavorText: '"Your sign in that yard is the best marketing you can do."',
    effect: {
      addTierA: 1,
      addTierC: 15,
      addCash: 8000,
      message: 'Anchor listing in Brookside. Premium exposure, 15 new sphere contacts, and a strong GCI deal.',
    },
    weight: 6,
  },
  {
    id: 'kc-opp-church-network',
    name: 'Church Referral Network',
    type: 'opportunity',
    emoji: '⛪',
    description: 'The pastor\'s family mentioned you to the congregation.',
    flavorText: '"In Kansas City, church community trust is worth more than any ad."',
    effect: {
      addTierC: 20,
      addTierB: 5,
      burnoutDelta: -10,
      message: 'Church referral network activated. 25 new contacts, 5 warm prospects. Community trust is the secret weapon.',
    },
    weight: 6,
  },
  {
    id: 'kc-opp-corporate-campus',
    name: 'Corporate Campus Relocation',
    type: 'opportunity',
    emoji: '🏢',
    description: 'Overland Park HQ is relocating 50 employees from out of state. You\'re their preferred agent.',
    flavorText: '"Ongoing relo pipeline."',
    effect: {
      addTierB: 8,
      addTierC: 12,
      burnoutDelta: 5,
      message: 'Corporate relocation partnership. 20 leads in pipeline. Work the list — this is 6 months of deal flow.',
    },
    weight: 5,
  },
  {
    id: 'kc-lead-estate-sale',
    name: 'Estate Sale Exclusive',
    type: 'lead',
    emoji: '📜',
    description: 'An estate attorney referred you to a family selling their grandparents\' farm. 40 acres.',
    flavorText: '"No competition."',
    effect: {
      addTierA: 1,
      addCash: 10000,
      addTierB: 3,
      message: 'Estate sale exclusive. Motivated heirs, realistic price. A-tier listing + 3 buyer inquiries from day one.',
    },
    weight: 6,
  },
  {
    id: 'kc-opp-teacher-program',
    name: 'Teacher/Nurse First-Time Buyer Program',
    type: 'opportunity',
    emoji: '🎓',
    description: 'Missouri launched a first-time buyer program for educators and healthcare workers. You\'re one of three approved agents.',
    flavorText: '"Applications are flooding in."',
    effect: {
      addTierB: 5,
      addTierC: 10,
      burnoutDelta: -5,
      message: 'Government buyer program referrals. 15 new contacts, 5 warm leads. Stable, motivated, community-rooted buyers.',
    },
    weight: 6,
  },
  {
    id: 'kc-market-chiefs',
    name: 'Kansas City Chiefs Effect',
    type: 'market-event',
    emoji: '🏈',
    description: 'A Super Bowl win sparked local pride and a migration surge. New buyers everywhere.',
    flavorText: '"The city is on the map."',
    effect: {
      addTierB: 4,
      addTierC: 8,
      marketMultiplier: 1.20,
      marketMultiplierRounds: 2,
      message: 'Chiefs effect: market boost + 12 new leads from national migration attention.',
    },
    weight: 5,
  },
  {
    id: 'kc-opp-steady-closer',
    name: 'Steady Closer Quarter',
    type: 'opportunity',
    emoji: '📈',
    description: 'Nothing flashy. You just worked your database, kept your appointments, and closed four deals.',
    flavorText: '"Midwest grind."',
    effect: {
      addCash: 25000,
      addPendingDeals: 2,
      burnoutDelta: -15,
      message: 'Textbook quarter. Four closes, $25K GCI advance, pipeline growing. Steady beats spectacular.',
    },
    weight: 6,
  },
];

// ── DETROIT ───────────────────────────────────────────────────────────────

const DETROIT_CARDS: CardDef[] = [
  // TROUBLE CARDS
  {
    id: 'det-trap-title',
    name: 'Title Nightmare',
    type: 'trap',
    emoji: '📜',
    description: 'Chain of title goes back to 1987. Three unpaid judgments and a mechanic\'s lien from 1994.',
    flavorText: '"Nobody signed the release."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 20,
      addCash: -3000,
      message: 'Title nightmare. Three encumbrances, one quiet-title action, and $3K in title resolution costs.',
    },
    weight: 8,
  },
  {
    id: 'det-trap-blight',
    name: 'Blight Ordinance Block',
    type: 'trap',
    emoji: '🏚️',
    description: 'The city flagged your property for blight ordinance violations before closing.',
    flavorText: '"Seller didn\'t know. You didn\'t know. Now you both know."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      addTierA: 1,
      message: 'Blight ordinance halt. Deal pushed to next quarter while violations are remediated.',
    },
    weight: 7,
  },
  {
    id: 'det-trap-investor-outbid',
    name: 'Investor Outbid — Cash Offer',
    type: 'trap',
    emoji: '💰',
    description: 'Your buyer offered fair market value. An investor group offered $15K over in cash.',
    flavorText: '"7-day close. Your buyer never had a chance."',
    effect: {
      addTierA: -1,
      burnoutDelta: 15,
      message: 'Cash investor outbid your retail buyer. Detroit investors move fast. Prep buyers better.',
    },
    weight: 8,
  },
  {
    id: 'det-trap-environmental',
    name: 'Environmental Report Surprise',
    type: 'trap',
    emoji: '☣️',
    description: 'Phase I study: soil contamination from a 1960s industrial operation three lots over.',
    flavorText: '"Buyer\'s lender withdrew."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 22,
      message: 'Environmental contamination found. Lender pulled out, deal dead. Always order Phase I on commercial-adjacent properties.',
    },
    weight: 7,
  },
  {
    id: 'det-trap-vandalism',
    name: 'Vacant Property Vandalism',
    type: 'trap',
    emoji: '🔨',
    description: 'Your vacant listing was broken into. Copper pipes stripped. HVAC gone.',
    flavorText: '"$18,000 in damage. Closing suspended pending repairs."',
    effect: {
      addCash: -4000,
      burnoutDelta: 18,
      addPendingDeals: -1,
      addTierA: 1,
      message: 'Vacant listing vandalized. Repairs needed before closing. $4K out of pocket, deal back to A-tier.',
    },
    weight: 7,
  },
  {
    id: 'det-trap-schools',
    name: 'Detroit Schools Rating Pushback',
    type: 'trap',
    emoji: '🏫',
    description: 'Your buyer researched school ratings. They\'re relocating from the suburbs and won\'t budge.',
    flavorText: '"Deal off."',
    effect: {
      addTierB: -1,
      burnoutDelta: 12,
      message: 'School district concerns killed a buyer deal. Know your clients\' non-negotiables upfront.',
    },
    weight: 7,
  },
  {
    id: 'det-trap-portfolio-dispute',
    name: 'Bulk Portfolio Dispute',
    type: 'trap',
    emoji: '📋',
    description: 'Investor signed to buy 8 properties. Due diligence found 3 with serious deferred maintenance.',
    flavorText: '"They\'re renegotiating everything — downward."',
    effect: {
      addCash: -8000,
      burnoutDelta: 20,
      message: 'Bulk portfolio renegotiation. Lost $8K in commission on revised terms.',
    },
    weight: 6,
  },
  {
    id: 'det-trap-backlash',
    name: 'Gentrification Backlash',
    type: 'trap',
    emoji: '📣',
    description: 'Community activists organized a protest against the investor group you\'re representing.',
    flavorText: '"Your listing is in a transitional neighborhood."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 20,
      addCash: -2000,
      message: 'Community pushback on investor purchase. Deal paused, $2K in PR/legal consultation.',
    },
    weight: 6,
  },
  // VICTORY CARDS
  {
    id: 'det-opp-taxcredit',
    name: 'Revitalization Zone Tax Credit',
    type: 'opportunity',
    emoji: '🏛️',
    description: 'Your buyer discovered the property qualifies for a federal Opportunity Zone tax credit.',
    flavorText: '"Suddenly the numbers make sense."',
    effect: {
      addPendingDeals: 2,
      addCash: 8000,
      burnoutDelta: -5,
      message: 'Opportunity Zone tax credit made two deals pencil out. $8K advance plus two more pending closes.',
    },
    weight: 6,
  },
  {
    id: 'det-opp-portfolio-sweep',
    name: 'Investor Portfolio Sweep',
    type: 'opportunity',
    emoji: '💼',
    description: 'A Detroit-based investment group wants to acquire 10 properties in Q1.',
    flavorText: '"You\'re the call."',
    effect: {
      addTierA: 3,
      addCash: 20000,
      burnoutDelta: 10,
      message: 'Investor portfolio engagement. 10-property sweep. $20K advance, 3 A-tier deals in motion.',
    },
    weight: 5,
  },
  {
    id: 'det-lead-historic',
    name: 'Historic Tax Credit Property',
    type: 'lead',
    emoji: '🏛️',
    description: 'A developer wants to restore a historic warehouse. They need an agent familiar with historic tax credits.',
    flavorText: '"You just became that agent."',
    effect: {
      addTierA: 1,
      addCash: 18000,
      addTierC: 8,
      message: 'Historic tax credit deal in your pipeline. High complexity, high commission. Niche expertise commands a premium.',
    },
    weight: 5,
  },
  {
    id: 'det-market-comeback',
    name: 'Detroit Comeback Story',
    type: 'market-event',
    emoji: '📺',
    description: 'A major media outlet runs a "Detroit Comeback" piece. National buyers flood in.',
    flavorText: '"Your phone rings all week."',
    effect: {
      addTierB: 5,
      addTierC: 10,
      marketMultiplier: 1.25,
      marketMultiplierRounds: 2,
      message: 'Media-driven Detroit surge. 15 new leads, market up 25% for 2 quarters. Ride the momentum.',
    },
    weight: 5,
  },
  {
    id: 'det-opp-bulk-close',
    name: 'Bulk Package Close',
    type: 'opportunity',
    emoji: '📦',
    description: 'You packaged 6 distressed properties into a single sale for an institutional buyer.',
    flavorText: '"More work than 6 normal transactions — pays like 10."',
    effect: {
      addCash: 35000,
      burnoutDelta: 5,
      message: 'Bulk portfolio closed. 6 properties, single transaction, premium commission.',
    },
    weight: 5,
  },
  {
    id: 'det-opp-nonprofit',
    name: 'Nonprofit Developer Partner',
    type: 'opportunity',
    emoji: '🤝',
    description: 'A nonprofit housing authority selected you for a 50-home revitalization project. 18-month engagement.',
    flavorText: '"Mission-driven and profitable."',
    effect: {
      addTierB: 6,
      addPassiveIncomeMonthly: 1500,
      burnoutDelta: -10,
      message: 'Nonprofit housing partner. 6 leads now + $1,500/mo retainer for ongoing acquisitions.',
    },
    weight: 5,
  },
  {
    id: 'det-opp-auction',
    name: 'Auction Win — Discounted Buy',
    type: 'opportunity',
    emoji: '🔨',
    description: 'You attended a Wayne County tax auction and secured a solid property at 40 cents on the dollar.',
    flavorText: '"They\'re ecstatic."',
    effect: {
      addTierB: 3,
      addTierC: 10,
      addCash: 7000,
      burnoutDelta: -8,
      message: 'Tax auction win. Buyer got a steal, you got a commission and referrals for life.',
    },
    weight: 6,
  },
  {
    id: 'det-lead-tech-district',
    name: 'Detroit Tech District Buyer',
    type: 'lead',
    emoji: '💻',
    description: 'The tech district expansion brought in 200 new employees. Three want live-work lofts.',
    flavorText: '"They want walkability and character."',
    effect: {
      addTierA: 2,
      addTierB: 3,
      burnoutDelta: -5,
      message: 'Tech district buyers engaged. 2 A-tier, 3 B-tier. Educated, decisive, good credit.',
    },
    weight: 6,
  },
];

// ── LAS VEGAS ─────────────────────────────────────────────────────────────

const LAS_VEGAS_CARDS: CardDef[] = [
  // TROUBLE CARDS
  {
    id: 'lv-trap-flashcrash',
    name: 'Market Flash Crash',
    type: 'trap',
    emoji: '📉',
    description: 'Overextended investors panic-sold. The market dropped 18% in 6 weeks.',
    flavorText: '"Your four pending deals are all being renegotiated."',
    effect: {
      marketMultiplier: 0.55,
      marketMultiplierRounds: 2,
      addPendingDeals: -2,
      burnoutDelta: 25,
      message: 'Flash crash. Market down 45%. Two deals renegotiated out of existence. Vegas peaks always precede valleys.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-flippers',
    name: 'Out-of-State Flippers Flood',
    type: 'trap',
    emoji: '🔄',
    description: 'Phoenix investors bought 300 houses last quarter and are now selling them all at once.',
    flavorText: '"Your listing is competing with 299 others just like it."',
    effect: {
      marketMultiplier: 0.75,
      marketMultiplierRounds: 2,
      burnoutDelta: 15,
      message: 'Flipper exit flood. 300 competing listings hit at once. Market suppressed 25% for 2 quarters.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-casino-cancelled',
    name: 'Casino Exec Relo Cancelled',
    type: 'trap',
    emoji: '🎲',
    description: 'The casino exec\'s relocation fell through. Their position was eliminated in a corporate restructure.',
    flavorText: '"Your A-tier buyer is gone."',
    effect: {
      addTierA: -1,
      burnoutDelta: 18,
      message: 'Casino exec relo cancelled. Corporate restructure eliminated the position and your buyer.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-convention',
    name: 'Convention Season Dead Zone',
    type: 'trap',
    emoji: '🚫',
    description: 'Three major conventions blocked your buyers from touring. Nobody deals during CES.',
    flavorText: '"You wait."',
    effect: {
      marketMultiplier: 0.70,
      marketMultiplierRounds: 1,
      burnoutDelta: 15,
      message: 'Convention season lockout. A full quarter of suppressed buyer activity. Work your sphere instead.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-hoa',
    name: 'HOA Disaster',
    type: 'trap',
    emoji: '🏢',
    description: 'The HOA has $400K in deferred maintenance and a $25,000 special assessment per unit.',
    flavorText: '"Your buyer ran."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      message: 'HOA special assessment killed the deal. $25K surprise was a deal-breaker. Always pull HOA financials.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-stampede',
    name: 'Investor Exit Stampede',
    type: 'trap',
    emoji: '🏃',
    description: 'Interest rates ticked up 0.75% and every investor in your pipeline hit pause simultaneously.',
    flavorText: '"Seven conversations went silent in 48 hours."',
    effect: {
      addTierB: -3,
      addTierA: -1,
      burnoutDelta: 20,
      message: 'Rate sensitivity caused investor stampede. Lost 4 leads in 48 hours. Vegas investors have no loyalty to timeline.',
    },
    weight: 7,
  },
  {
    id: 'lv-trap-underwater',
    name: 'Underwater Seller',
    type: 'trap',
    emoji: '🌊',
    description: 'Your seller bought at peak 2022 prices. They owe more than the home is worth.',
    flavorText: '"Short sale territory. Long, painful process."',
    effect: {
      addCash: -2000,
      burnoutDelta: 22,
      message: 'Short sale situation. Bank approval required. $2K in carrying costs, 6 months to close.',
    },
    weight: 6,
  },
  {
    id: 'lv-trap-speculative',
    name: 'Speculative Buyer Backs Out',
    type: 'trap',
    emoji: '🎰',
    description: 'Your buyer was gambling on appreciation. The market softened 8% since they made the offer.',
    flavorText: '"Walking away from their earnest money."',
    effect: {
      addPendingDeals: -1,
      burnoutDelta: 15,
      message: 'Speculative buyer forfeited earnest money and walked. Not your fault — but still your lost commission.',
    },
    weight: 7,
  },
  // VICTORY CARDS
  {
    id: 'lv-lead-casino-exec',
    name: 'Casino Exec Relocation',
    type: 'lead',
    emoji: '🎲',
    description: 'A high-roller casino executive needs a home yesterday. Budget: $1.5M.',
    flavorText: '"Decision in 72 hours."',
    effect: {
      addTierA: 1,
      addPendingDeals: 1,
      addCash: 15000,
      message: 'Casino exec relo. $1.5M budget, 72-hour decision. Already got one in pending. Vegas executives move fast.',
    },
    weight: 6,
  },
  {
    id: 'lv-market-boom',
    name: 'Boom Quarter',
    type: 'market-event',
    emoji: '🚀',
    description: 'National media called Las Vegas the hottest market in America. Cash buyers flooded in.',
    flavorText: '"12 inbound calls this week."',
    effect: {
      marketMultiplier: 1.50,
      marketMultiplierRounds: 2,
      addTierB: 6,
      addTierC: 10,
      message: 'Boom quarter. Market up 50% for 2 quarters, 16 new leads. This is Vegas — ride the wave.',
    },
    weight: 5,
  },
  {
    id: 'lv-opp-mogul',
    name: 'Entertainment Mogul Purchase',
    type: 'opportunity',
    emoji: '🎬',
    description: 'A music executive is buying a compound near the Strip. Budget: $3.5M.',
    flavorText: '"Needs privacy, a home theater, and a guest house."',
    effect: {
      addCash: 45000,
      addPendingDeals: 1,
      message: 'Entertainment mogul purchase. $3.5M, fast close, full commission. $45K GCI. Keep this client for life.',
    },
    weight: 5,
  },
  {
    id: 'lv-opp-str-investor',
    name: 'Short-Term Rental Investor',
    type: 'opportunity',
    emoji: '🏨',
    description: 'A client wants to build a portfolio of Airbnb properties near the Strip. 6 properties this year.',
    flavorText: '"They want you to find all of them."',
    effect: {
      addTierA: 2,
      addTierB: 4,
      addCash: 18000,
      message: 'STR investor portfolio. 6 deals this year, you\'re their exclusive agent. $18K advance + 5 more in pipeline.',
    },
    weight: 5,
  },
  {
    id: 'lv-market-f1',
    name: 'F1 Vegas Grand Prix Effect',
    type: 'market-event',
    emoji: '🏎️',
    description: 'Formula 1 announced a 10-year contract. Luxury condo demand near the Strip exploded.',
    flavorText: '"Vegas just got a decade of attention."',
    effect: {
      addTierB: 4,
      addTierC: 8,
      marketMultiplier: 1.30,
      marketMultiplierRounds: 3,
      message: 'F1 effect. Luxury demand surged. 12 new leads + 30% market lift for 3 quarters.',
    },
    weight: 5,
  },
  {
    id: 'lv-market-remote',
    name: 'Remote Worker Migration Wave',
    type: 'market-event',
    emoji: '💻',
    description: 'California remote workers discovered zero state income tax and warm weather. Moving in waves.',
    flavorText: '"5 calls a week."',
    effect: {
      addTierB: 5,
      addTierC: 12,
      burnoutDelta: -8,
      message: 'Remote worker migration wave. 17 new leads, mostly CA buyers with equity to deploy.',
    },
    weight: 5,
  },
  {
    id: 'lv-opp-preconstruction',
    name: 'Pre-Construction Play',
    type: 'opportunity',
    emoji: '🏗️',
    description: 'You got access to a pre-construction condo tower near the Strip. First 20 units at pre-launch pricing.',
    flavorText: '"Buyers need to decide this week."',
    effect: {
      addTierA: 3,
      addCash: 25000,
      burnoutDelta: 10,
      message: 'Pre-construction access. 3 A-tier buyers committed. $25K advance on projected closes.',
    },
    weight: 5,
  },
  {
    id: 'lv-opp-equity-migration',
    name: 'Out-of-State Equity Migration',
    type: 'opportunity',
    emoji: '🌴',
    description: 'Five California buyers sold their homes for 2–3x value and landed in Vegas with $600K–$1M.',
    flavorText: '"They want something now."',
    effect: {
      addTierA: 5,
      addPendingDeals: 2,
      burnoutDelta: 5,
      message: 'California equity migration. Five buyers with cash, no contingencies, ready now. Two already in pending.',
    },
    weight: 5,
  },
];

// ── Export ────────────────────────────────────────────────────────────────

export const CITY_CARDS: Record<CityId, CardDef[]> = {
  'new-york': NEW_YORK_CARDS,
  'beverly-hills': BEVERLY_HILLS_CARDS,
  'kansas-city': KANSAS_CITY_CARDS,
  'detroit': DETROIT_CARDS,
  'las-vegas': LAS_VEGAS_CARDS,
};
